#!/bin/bash

git add src/*.hpp src/*.cpp src/Standard/*.cpp src/Standard/*.hpp
git add Assets/Textures/*.png Assets/Models/*.blend Assets/Models/*.pmf
git add Makefile gitupdate replace check-mem.sh
git add BlenderScripts/*

git commit -m $1
git push
