CXX=g++-5
PREPROCESS=cpp
EXPANDER=expander.py #--eval "def inc(filename):"
EXPANDER_EXT=ii
CXXFLAGS= -Werror -Wall -std=c++1y -fno-rtti
INCLUDE = -Isrc/Standard -IThirdParty/include
SOURCES=$(wildcard src/*.cpp) $(wildcard src/Standard/*.cpp)
EXPANSIONS=$(SOURCES:.cpp=.$(EXPANDER_EXT))
OBJECTS=$(SOURCES:.cpp=.o)
OUTDIR = bin/
EXECUTABLE= $(OUTDIR)peace

UNAME = $(shell uname)

ifeq ($(UNAME), Linux)
LIBS = -lX11 -lXxf86vm -lXcursor -lXinerama -lXrandr -lXext -lXi -lGL
LIBDIR = -LThirdParty/lib/Linux
endif
ifeq ($(UNAME), Darwin)
LIBS = -framework OpenGL -framework Cocoa -framework IOKit -framework CoreVideo -framework CoreFoundation
LIBDIR = -LThirdParty/lib/OSX
endif

LIBS += -lGLEW -lglfw3 -lSOIL -lpthread

debug: CXXFLAGS += -rdynamic -ggdb
debug: $(SOURCES) $(EXECUTABLE)

release: CXXFLAGS += -O3
release: $(SOURCES) $(EXECUTABLE)	

all: debug

depend:
	@makedepend $(SOURCES)
	@./finalize-depend Makefile

$(EXECUTABLE): $(OBJECTS)
	$(CXX) $(LIBDIR) $(LIBS) $(LIBS) $(OBJECTS) -o $@ $(LIBS) $(LIBS)

%.o: %.$(EXPANDER_EXT)
	$(CXX) $(CXXFLAGS) $(INCLUDE) -c -o $@ $<

%.$(EXPANDER_EXT): %.cpp
	$(PREPROCESS) -x c++ $(CXXFLAGS) $<  $(INCLUDE) | $(EXPANDER) "/dev/stdin" > $@

clean:
	@rm -f $(OBJECTS) $(EXPANSIONS) $(EXECUTABLE)

.SUFFIXES:
#.SECONDARY:
# DO NOT DELETE

src/Assets.ii: /usr/include/unistd.h /usr/include/features.h
src/Assets.ii: /usr/include/stdc-predef.h /usr/include/getopt.h src/Assets.hpp
src/BonedMesh.ii: src/BonedMesh.hpp src/StaticMesh.hpp src/Renderable.hpp
src/BonedMesh.ii: src/VertexObjects.hpp src/GL.hpp src/Shader.hpp
src/BonedMesh.ii: src/Vector.hpp src/Math.hpp /usr/include/string.h
src/BonedMesh.ii: /usr/include/features.h /usr/include/stdc-predef.h
src/BonedMesh.ii: /usr/include/xlocale.h /usr/include/math.h src/Matrix.hpp
src/BonedMesh.ii: src/Texture.hpp src/BasicMesh.hpp src/BoundingObject.hpp
src/BonedMesh.ii: src/Quaternion.hpp src/Transform.hpp
src/BoundingObject.ii: src/BoundingObject.hpp src/Vector.hpp src/Math.hpp
src/BoundingObject.ii: /usr/include/string.h /usr/include/features.h
src/BoundingObject.ii: /usr/include/stdc-predef.h /usr/include/xlocale.h
src/BoundingObject.ii: /usr/include/math.h src/Matrix.hpp src/BasicMesh.hpp
src/BoundingObject.ii: src/Node.hpp src/Transform.hpp src/Quaternion.hpp
src/BoundingObject.ii: src/Renderable.hpp src/VertexObjects.hpp src/GL.hpp
src/BoundingObject.ii: src/Shader.hpp
src/Camera.ii: src/Camera.hpp src/Vector.hpp src/Math.hpp
src/Camera.ii: /usr/include/string.h /usr/include/features.h
src/Camera.ii: /usr/include/stdc-predef.h /usr/include/xlocale.h
src/Camera.ii: /usr/include/math.h src/Matrix.hpp src/Quaternion.hpp
src/Camera.ii: src/Transform.hpp src/GL.hpp
src/Collision.ii: src/Collision.hpp src/PhysicalObject.hpp src/Node.hpp
src/Collision.ii: src/Transform.hpp src/Vector.hpp src/Math.hpp
src/Collision.ii: /usr/include/string.h /usr/include/features.h
src/Collision.ii: /usr/include/stdc-predef.h /usr/include/xlocale.h
src/Collision.ii: /usr/include/math.h src/Matrix.hpp src/Quaternion.hpp
src/Collision.ii: src/Renderable.hpp src/VertexObjects.hpp src/GL.hpp
src/Collision.ii: src/Shader.hpp src/Messageable.hpp src/Contact.hpp
src/Collision.ii: src/BoundingObject.hpp src/BasicMesh.hpp
src/Contact.ii: src/Contact.hpp src/BoundingObject.hpp src/Vector.hpp
src/Contact.ii: src/Math.hpp /usr/include/string.h /usr/include/features.h
src/Contact.ii: /usr/include/stdc-predef.h /usr/include/xlocale.h
src/Contact.ii: /usr/include/math.h src/Matrix.hpp src/BasicMesh.hpp
src/GL.ii: src/GL.hpp
src/Graphics.ii: src/Graphics.hpp src/Light.hpp src/Vector.hpp src/Math.hpp
src/Graphics.ii: /usr/include/string.h /usr/include/features.h
src/Graphics.ii: /usr/include/stdc-predef.h /usr/include/xlocale.h
src/Graphics.ii: /usr/include/math.h src/Shader.hpp src/GL.hpp src/Matrix.hpp
src/Graphics.ii: src/Camera.hpp src/Quaternion.hpp src/Transform.hpp
src/Graphics.ii: src/Node.hpp src/Renderable.hpp src/VertexObjects.hpp
src/Graphics.ii: src/GUI.hpp src/Texture.hpp src/Input.hpp
src/GUI.ii: src/GUI.hpp src/Renderable.hpp src/VertexObjects.hpp src/GL.hpp
src/GUI.ii: src/Shader.hpp src/Vector.hpp src/Math.hpp /usr/include/string.h
src/GUI.ii: /usr/include/features.h /usr/include/stdc-predef.h
src/GUI.ii: /usr/include/xlocale.h /usr/include/math.h src/Matrix.hpp
src/GUI.ii: src/Texture.hpp src/BoundingObject.hpp src/BasicMesh.hpp
src/GUI.ii: src/Graphics.hpp src/Light.hpp src/Assets.hpp
src/GUIWidgets.ii: src/GUIWidgets.hpp src/GUI.hpp src/Renderable.hpp
src/GUIWidgets.ii: src/VertexObjects.hpp src/GL.hpp src/Shader.hpp
src/GUIWidgets.ii: src/Vector.hpp src/Math.hpp /usr/include/string.h
src/GUIWidgets.ii: /usr/include/features.h /usr/include/stdc-predef.h
src/GUIWidgets.ii: /usr/include/xlocale.h /usr/include/math.h src/Matrix.hpp
src/GUIWidgets.ii: src/Texture.hpp
src/Input.ii: src/Input.hpp src/GL.hpp
src/Light.ii: src/Light.hpp src/Vector.hpp src/Math.hpp /usr/include/string.h
src/Light.ii: /usr/include/features.h /usr/include/stdc-predef.h
src/Light.ii: /usr/include/xlocale.h /usr/include/math.h
src/main.ii: src/Graphics.hpp src/Light.hpp src/Vector.hpp src/Math.hpp
src/main.ii: /usr/include/string.h /usr/include/features.h
src/main.ii: /usr/include/stdc-predef.h /usr/include/xlocale.h
src/main.ii: /usr/include/math.h src/Shader.hpp src/GL.hpp src/Matrix.hpp
src/main.ii: src/GUIWidgets.hpp src/GUI.hpp src/Renderable.hpp
src/main.ii: src/VertexObjects.hpp src/Texture.hpp src/Input.hpp
src/main.ii: src/StaticMesh.hpp src/BasicMesh.hpp src/BoundingObject.hpp
src/main.ii: src/MeshLoader.hpp src/BonedMesh.hpp src/Quaternion.hpp
src/main.ii: src/Transform.hpp src/Node.hpp src/Camera.hpp src/Physics.hpp
src/main.ii: src/PhysicalObject.hpp src/Messageable.hpp src/Assets.hpp
src/MeshLoader.ii: src/MeshLoader.hpp src/BonedMesh.hpp src/StaticMesh.hpp
src/MeshLoader.ii: src/Renderable.hpp src/VertexObjects.hpp src/GL.hpp
src/MeshLoader.ii: src/Shader.hpp src/Vector.hpp src/Math.hpp
src/MeshLoader.ii: /usr/include/string.h /usr/include/features.h
src/MeshLoader.ii: /usr/include/stdc-predef.h /usr/include/xlocale.h
src/MeshLoader.ii: /usr/include/math.h src/Matrix.hpp src/Texture.hpp
src/MeshLoader.ii: src/BasicMesh.hpp src/BoundingObject.hpp src/Quaternion.hpp
src/MeshLoader.ii: src/Transform.hpp src/Assets.hpp
src/Node.ii: src/Node.hpp src/Transform.hpp src/Vector.hpp src/Math.hpp
src/Node.ii: /usr/include/string.h /usr/include/features.h
src/Node.ii: /usr/include/stdc-predef.h /usr/include/xlocale.h
src/Node.ii: /usr/include/math.h src/Matrix.hpp src/Quaternion.hpp
src/Node.ii: src/Renderable.hpp src/VertexObjects.hpp src/GL.hpp
src/Node.ii: src/Shader.hpp src/BoundingObject.hpp src/BasicMesh.hpp
src/PhysicalObject.ii: src/PhysicalObject.hpp src/Node.hpp src/Transform.hpp
src/PhysicalObject.ii: src/Vector.hpp src/Math.hpp /usr/include/string.h
src/PhysicalObject.ii: /usr/include/features.h /usr/include/stdc-predef.h
src/PhysicalObject.ii: /usr/include/xlocale.h /usr/include/math.h
src/PhysicalObject.ii: src/Matrix.hpp src/Quaternion.hpp src/Renderable.hpp
src/PhysicalObject.ii: src/VertexObjects.hpp src/GL.hpp src/Shader.hpp
src/PhysicalObject.ii: src/Messageable.hpp src/BoundingObject.hpp
src/PhysicalObject.ii: src/BasicMesh.hpp
src/Physics.ii: src/Physics.hpp src/PhysicalObject.hpp src/Node.hpp
src/Physics.ii: src/Transform.hpp src/Vector.hpp src/Math.hpp
src/Physics.ii: /usr/include/string.h /usr/include/features.h
src/Physics.ii: /usr/include/stdc-predef.h /usr/include/xlocale.h
src/Physics.ii: /usr/include/math.h src/Matrix.hpp src/Quaternion.hpp
src/Physics.ii: src/Renderable.hpp src/VertexObjects.hpp src/GL.hpp
src/Physics.ii: src/Shader.hpp src/Messageable.hpp src/Collision.hpp
src/Renderable.ii: src/Renderable.hpp src/VertexObjects.hpp src/GL.hpp
src/Renderable.ii: src/Shader.hpp src/Vector.hpp src/Math.hpp
src/Renderable.ii: /usr/include/string.h /usr/include/features.h
src/Renderable.ii: /usr/include/stdc-predef.h /usr/include/xlocale.h
src/Renderable.ii: /usr/include/math.h src/Matrix.hpp
src/Shader.ii: src/Shader.hpp src/GL.hpp src/Vector.hpp src/Math.hpp
src/Shader.ii: /usr/include/string.h /usr/include/features.h
src/Shader.ii: /usr/include/stdc-predef.h /usr/include/xlocale.h
src/Shader.ii: /usr/include/math.h src/Matrix.hpp src/Color.hpp src/Assets.hpp
src/StaticMesh.ii: src/StaticMesh.hpp src/Renderable.hpp src/VertexObjects.hpp
src/StaticMesh.ii: src/GL.hpp src/Shader.hpp src/Vector.hpp src/Math.hpp
src/StaticMesh.ii: /usr/include/string.h /usr/include/features.h
src/StaticMesh.ii: /usr/include/stdc-predef.h /usr/include/xlocale.h
src/StaticMesh.ii: /usr/include/math.h src/Matrix.hpp src/Texture.hpp
src/StaticMesh.ii: src/BasicMesh.hpp src/BoundingObject.hpp
src/Terrain.ii: src/Terrain.hpp src/StaticMesh.hpp src/Renderable.hpp
src/Terrain.ii: src/VertexObjects.hpp src/GL.hpp src/Shader.hpp src/Vector.hpp
src/Terrain.ii: src/Math.hpp /usr/include/string.h /usr/include/features.h
src/Terrain.ii: /usr/include/stdc-predef.h /usr/include/xlocale.h
src/Terrain.ii: /usr/include/math.h src/Matrix.hpp src/Texture.hpp
src/Terrain.ii: src/BasicMesh.hpp src/BoundingObject.hpp
src/Texture.ii: src/Texture.hpp src/GL.hpp src/Shader.hpp src/Vector.hpp
src/Texture.ii: src/Math.hpp /usr/include/string.h /usr/include/features.h
src/Texture.ii: /usr/include/stdc-predef.h /usr/include/xlocale.h
src/Texture.ii: /usr/include/math.h src/Matrix.hpp src/Assets.hpp
src/Transform.ii: src/Transform.hpp src/Vector.hpp src/Math.hpp
src/Transform.ii: /usr/include/string.h /usr/include/features.h
src/Transform.ii: /usr/include/stdc-predef.h /usr/include/xlocale.h
src/Transform.ii: /usr/include/math.h src/Matrix.hpp src/Quaternion.hpp
src/Transform.ii: src/Shader.hpp src/GL.hpp
src/VertexObjects.ii: src/VertexObjects.hpp src/GL.hpp src/Shader.hpp
src/VertexObjects.ii: src/Vector.hpp src/Math.hpp /usr/include/string.h
src/VertexObjects.ii: /usr/include/features.h /usr/include/stdc-predef.h
src/VertexObjects.ii: /usr/include/xlocale.h /usr/include/math.h
src/VertexObjects.ii: src/Matrix.hpp
src/Standard/Exception.ii: src/Standard/Exception.hpp /usr/include/stdlib.h
src/Standard/Exception.ii: /usr/include/features.h /usr/include/stdc-predef.h
src/Standard/Exception.ii: /usr/include/alloca.h /usr/include/execinfo.h
src/Standard/Exception.ii: src/Standard/Macros.hpp /usr/include/stdio.h
src/Standard/Exception.ii: /usr/include/libio.h /usr/include/_G_config.h
src/Standard/Exception.ii: /usr/include/wchar.h /usr/include/xlocale.h
src/Standard/Exception.ii: src/Standard/Types.hpp /usr/include/stdint.h
src/Standard/Exception.ii: src/Standard/String.hpp src/Standard/Log.hpp
src/Standard/Exception.ii: src/Standard/EventManager.hpp
src/Standard/Exception.ii: src/Standard/Containers.hpp
src/Standard/Exception.ii: src/Standard/Function.hpp src/Standard/System.hpp
src/Standard/Exception.ii: src/Standard/Thread.hpp
src/Standard/FileIO.ii: src/Standard/FileIO.hpp /usr/include/stdio.h
src/Standard/FileIO.ii: /usr/include/features.h /usr/include/stdc-predef.h
src/Standard/FileIO.ii: /usr/include/libio.h /usr/include/_G_config.h
src/Standard/FileIO.ii: /usr/include/wchar.h /usr/include/xlocale.h
src/Standard/FileIO.ii: /usr/include/stdint.h src/Standard/Macros.hpp
src/Standard/FileIO.ii: /usr/include/stdlib.h /usr/include/alloca.h
src/Standard/FileIO.ii: src/Standard/Log.hpp src/Standard/String.hpp
src/Standard/FileIO.ii: src/Standard/EventManager.hpp
src/Standard/FileIO.ii: src/Standard/Containers.hpp src/Standard/Types.hpp
src/Standard/FileIO.ii: src/Standard/Function.hpp src/Standard/System.hpp
src/Standard/FileIO.ii: src/Standard/Thread.hpp src/Standard/Exception.hpp
src/Standard/FileIO.ii: /usr/include/execinfo.h
src/Standard/Log.ii: src/Standard/Log.hpp src/Standard/Macros.hpp
src/Standard/Log.ii: /usr/include/stdio.h /usr/include/features.h
src/Standard/Log.ii: /usr/include/stdc-predef.h /usr/include/libio.h
src/Standard/Log.ii: /usr/include/_G_config.h /usr/include/wchar.h
src/Standard/Log.ii: /usr/include/xlocale.h /usr/include/stdlib.h
src/Standard/Log.ii: /usr/include/alloca.h src/Standard/String.hpp
src/Standard/Log.ii: src/Standard/EventManager.hpp src/Standard/Containers.hpp
src/Standard/Log.ii: src/Standard/Types.hpp /usr/include/stdint.h
src/Standard/Log.ii: src/Standard/Function.hpp src/Standard/System.hpp
src/Standard/Log.ii: src/Standard/Thread.hpp src/Standard/Exception.hpp
src/Standard/Log.ii: /usr/include/execinfo.h
src/Standard/String.ii: src/Standard/String.hpp src/Standard/Macros.hpp
src/Standard/String.ii: /usr/include/stdio.h /usr/include/features.h
src/Standard/String.ii: /usr/include/stdc-predef.h /usr/include/libio.h
src/Standard/String.ii: /usr/include/_G_config.h /usr/include/wchar.h
src/Standard/String.ii: /usr/include/xlocale.h /usr/include/stdlib.h
src/Standard/String.ii: /usr/include/alloca.h src/Standard/Containers.hpp
src/Standard/String.ii: src/Standard/Types.hpp /usr/include/stdint.h
src/Standard/String.ii: src/Standard/Function.hpp
src/Standard/System.ii: src/Standard/System.hpp src/Standard/Macros.hpp
src/Standard/System.ii: /usr/include/stdio.h /usr/include/features.h
src/Standard/System.ii: /usr/include/stdc-predef.h /usr/include/libio.h
src/Standard/System.ii: /usr/include/_G_config.h /usr/include/wchar.h
src/Standard/System.ii: /usr/include/xlocale.h /usr/include/stdlib.h
src/Standard/System.ii: /usr/include/alloca.h src/Standard/Containers.hpp
src/Standard/System.ii: src/Standard/Types.hpp /usr/include/stdint.h
src/Standard/System.ii: src/Standard/Function.hpp src/Standard/Thread.hpp
